kind: pipeline
type: docker
name: default

steps:
  - name: backend
    image: composer
    commands:
      - composer install

  - name: test
    image: php:7
    commands:
      - cp .env.example .env
      - php artisan key:generate
      - php artisan config:cache
      - ./vendor/bin/phpunit
