kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: composer
    commands:
      - composer install

  - name: test
    image: php:7
    commands:
      - php artisan key:generate
      - php artisan config:cache
      - vendor/bin/phpunit
